import { createAction } from '@reduxjs/toolkit';

export const FETCH_ADMIN_REQUEST_USERS = 'FETCH_ADMIN_REQUEST_USERS';
export const FETCH_ADMIN_SUCCESS_USERS = 'FETCH_ADMIN_SUCCESS_USERS';
export const FETCH_ADMIN_FAILURE_USERS = 'FETCH_ADMIN_FAILURE_USERS';
export const SET_ADMIN_PAGE_USERS = 'SET_ADMIN_PAGE_USERS';
export const SET_ADMIN_SORT_USERS = 'SET_ADMIN_SORT_USERS';
export const SET_ADMIN_FILTERS = 'SET_ADMIN_FILTERS';
