export const FETCH_AUDITORIAS_TABLE_REQUEST = 'FETCH_AUDITORIAS_TABLE_REQUEST';
export const FETCH_AUDITORIAS_TABLE_SUCCESS = 'FETCH_AUDITORIAS_TABLE_SUCCESS';
export const FETCH_AUDITORIAS_TABLE_FAILURE = 'FETCH_AUDITORIAS_TABLE_FAILURE';