export const FETCH_CHATS_BOTS_HORARIO_REQUEST = 'FETCH_CHATS_BOTS_HORARIO_REQUEST';
export const FETCH_CHATS_BOTS_HORARIO_SUCCESS = 'FETCH_CHATS_BOTS_HORARIO_SUCCESS';
export const FETCH_CHATS_BOTS_HORARIO_FAILURE = 'FETCH_CHATS_BOTS_HORARIO_FAILURE';
